pipeline{
	agent any
	
	stages{
	
		stage('Compile Stage'){
			steps{
				
					sh '''
          cd Student
          mvn compile 
    '''
		    }
	    }
	    
		stage('QA test Stage'){
			steps{
				
					sh '''
          cd Student
          mvn clean test package sonar:sonar
    '''
		    }
	    }
	    
	    
	
	    
	 }
	 post{
	  	always{
	  	 	junit 'Student/target/surefire-reports/*.xml'
	  	 }
	  	}
	 
}
