pipeline{
	agent any
	
	stages{
	
		stage('Compile Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn compile 
    '''
		    }
	    }
	    
		stage('QA test Stage'){
			steps{
				
					sh '''
          cd StudentTest
          mvn clean test package sonar:sonar
    '''
		    }
	    }
	    
	    
		stage('Deploy Stage'){
			steps{
				sh '''
				cd StudentTest
				ansible-playbook Demo.yml
			'''
		    }
	    }
	    
	 }
	 post{
	  	always{
	  	 	junit 'StudentTest/target/surefire-reports/*.xml'
	  	 }
	  	}
	 
}